spring:
  profiles:
    active:
      - dev
---
server:
  port: 8004
spring:
  application:
    name: EMPLOYEE-PROVIDER #不要使用下划线
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #告诉服务提供者要把服务注册到哪儿，注册中心的地址
---
server:
  port: 8005
spring:
  application:
    name: EMPLOYEE-PROVIDER #不要使用下划线
  profiles: emp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #告诉服务提供者要把服务注册到哪儿，注册中心的地址
